"""correção do bug de não detectar os valores padrões para as colunas causado pela configuração migration online do env py

Revision ID: ef8463e62ed2
Revises: dabbd2bda3b2
Create Date: 2026-07-17 10:36:43.025409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8463e62ed2'
down_revision: Union[str, Sequence[str], None] = 'dabbd2bda3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
